import type { Meta, StoryObj } from '@storybook/nextjs-vite'
import { AiExplainabilityLabel } from '@/components/blocks/ai-explainability-label-01'

function AiExplainabilityLabelDemo() {
  return (
    <AiExplainabilityLabel
      confidence="medium"
      explanation="This summary was generated by AI from your last 30 support tickets."
    />
  )
}

const meta = {
  title: 'Blocks/ai-explainability-label/AI Explainability Label 01',
  parameters: { layout: 'padded' },
  tags: ['autodocs'],
  render: () => <AiExplainabilityLabelDemo />,
} satisfies Meta

export default meta
type Story = StoryObj<typeof meta>

export const Default: Story = {}
